In [24]:
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as ptr 
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [25]:
data= pd.read_csv('parkinsons.csv')
data.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [26]:
features= data.drop(columns=['name', 'status'])
features

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0        119.992       157.302        74.997         0.00784   
1        122.400       148.650       113.819         0.00968   
2        116.682       131.111       111.555         0.01050   
3        116.676       137.871       111.366         0.00997   
4        116.014       141.781       110.655         0.01284   
..           ...           ...           ...             ...   
190      174.188       230.978        94.261         0.00459   
191      209.516       253.017        89.488         0.00564   
192      174.688       240.005        74.287         0.01360   
193      198.764       396.961        74.904         0.00740   
194      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0             0.00007   0.00370   0.00554     0.01109       0.04374   
1             0.00008   0.00465   0.00696     0.01394       0.06134   
2             0.00009   0.00544   0.00781     0.01633       0.05233   
3             0.00009   0.00502   0.00698     0.01505       0.05492   
4             0.00011   0.00655   0.00908     0.01966       0.06425   
..                ...       ...       ...         ...           ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087   
191           0.00003   0.00331   0.00292     0.00994       0.02751   
192           0.00008   0.00624   0.00564     0.01873       0.02308   
193           0.00004   0.00370   0.00390     0.01109       0.02296   
194           0.00003   0.00295   0.00317     0.00885       0.01884   

     MDVP:Shimmer(dB)  ...  MDVP:APQ  Shimmer:DDA      NHR     HNR      RPDE  \
0               0.426  ...   0.02971      0.06545  0.02211  21.033  0.414783   
1               0.626  ...   0.04368      0.09403  0.01929  19.085  0.458359   
2               0.482  ...   0.03590      0.08270  0.01309  20.651  0.429895   
3               0.517  ...   0.03772      0.08771  0.01353  20.644  0.434969   
4               0.584  ...   0.04465      0.10470  0.01767  19.649  0.417356   
..                ...  ...       ...          ...      ...     ...       ...   
190             0.405  ...   0.02745      0.07008  0.02764  19.517  0.448439   
191             0.263  ...   0.01879      0.04812  0.01810  19.147  0.431674   
192             0.256  ...   0.01667      0.03804  0.10715  17.883  0.407567   
193             0.241  ...   0.01588      0.03794  0.07223  19.020  0.451221   
194             0.190  ...   0.01373      0.03078  0.04398  21.209  0.462803   

          DFA   spread1   spread2        D2       PPE  
0    0.815285 -4.813031  0.266482  2.301442  0.284654  
1    0.819521 -4.075192  0.335590  2.486855  0.368674  
2    0.825288 -4.443179  0.311173  2.342259  0.332634  
3    0.819235 -4.117501  0.334147  2.405554  0.368975  
4    0.823484 -3.747787  0.234513  2.332180  0.410335  
..        ...       ...       ...       ...       ...  
190  0.657899 -6.538586  0.121952  2.657476  0.133050  
191  0.683244 -6.195325  0.129303  2.784312  0.168895  
192  0.655683 -6.787197  0.158453  2.679772  0.131728  
193  0.643956 -6.744577  0.207454  2.138608  0.123306  
194  0.664357 -5.724056  0.190667  2.555477  0.148569  

[195 rows x 22 columns]

In [27]:
data.max()

name                phon_R01_S50_6
MDVP:Fo(Hz)                260.105
MDVP:Fhi(Hz)                592.03
MDVP:Flo(Hz)                239.17
MDVP:Jitter(%)             0.03316
MDVP:Jitter(Abs)           0.00026
MDVP:RAP                   0.02144
MDVP:PPQ                   0.01958
Jitter:DDP                 0.06433
MDVP:Shimmer               0.11908
MDVP:Shimmer(dB)             1.302
Shimmer:APQ3               0.05647
Shimmer:APQ5                0.0794
MDVP:APQ                   0.13778
Shimmer:DDA                0.16942
NHR                        0.31482
HNR                         33.047
status                           1
RPDE                      0.685151
DFA                       0.825288
spread1                  -2.434031
spread2                   0.450493
D2                        3.671155
PPE                       0.527367
dtype: object

In [28]:
data.min()

name                phon_R01_S01_1
MDVP:Fo(Hz)                 88.333
MDVP:Fhi(Hz)               102.145
MDVP:Flo(Hz)                65.476
MDVP:Jitter(%)             0.00168
MDVP:Jitter(Abs)          0.000007
MDVP:RAP                   0.00068
MDVP:PPQ                   0.00092
Jitter:DDP                 0.00204
MDVP:Shimmer               0.00954
MDVP:Shimmer(dB)             0.085
Shimmer:APQ3               0.00455
Shimmer:APQ5                0.0057
MDVP:APQ                   0.00719
Shimmer:DDA                0.01364
NHR                        0.00065
HNR                          8.441
status                           0
RPDE                       0.25657
DFA                       0.574282
spread1                  -7.964984
spread2                   0.006274
D2                        1.423287
PPE                       0.044539
dtype: object

In [29]:
target= data['status']
target

0      1
1      1
2      1
3      1
4      1
      ..
190    0
191    0
192    0
193    0
194    0
Name: status, Length: 195, dtype: int64

In [30]:
scaler= StandardScaler()
scaler.fit(features)
import pickle
pickle.dump(scaler, open('par_scaler.pkl', 'wb'))

In [31]:
features= scaler.transform(features)

In [32]:
features

array([[-0.82929965, -0.43616456, -0.95203729, ...,  0.48047686,
        -0.21053082,  0.86888575],
       [-0.77097169, -0.53097409, -0.05772056, ...,  1.31118546,
         0.27507712,  1.80360503],
       [-0.90947638, -0.7231683 , -0.10987483, ...,  1.01768236,
        -0.10362861,  1.40266141],
       ...,
       [ 0.49557839,  0.47010361, -0.96839309, ..., -0.81807931,
         0.78033848, -0.83241014],
       [ 1.07876114,  2.19004398, -0.95417967, ..., -0.22906571,
        -0.63700298, -0.92610456],
       [ 1.45481664,  0.69224632, -0.88348115, ..., -0.43085284,
         0.45480231, -0.64505466]])

In [33]:
x_train, x_test, y_train, y_test= train_test_split(features, target, test_size= 0.33, random_state= 10)

In [34]:
#svm
from sklearn.svm import SVC

model= SVC(C= 7.5)
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.9538461538461539

In [35]:
import pickle
pickle.dump(model, open('par_model.pkl', 'wb'))

In [36]:
par_model= pickle.load(open('D:/Users/NITIN VERMA/Desktop/Code for basics ML/New Project/parkinson disease/par_model.pkl', 'rb'))
par_scaler= pickle.load(open('D:/Users/NITIN VERMA/Desktop/Code for basics ML/New Project/parkinson disease/par_scaler.pkl', 'rb'))

In [40]:
x= [[108.80700,134.65600,102.87400,0.00761,0.00007,0.00349,0.00486,0.01046,0.02719,0.25500,0.01483,0.01609,0.02067,0.04450,0.01036,21.02800,0.536009,0.819032,-4.649573,0.205558,1.986899,0.316700]]
x= par_scaler.transform(x)
par_model.predict(x)

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [39]:
x= [[129.33600,139.86700,118.60400,0.00490,0.00004,0.00165,0.00183,0.00495,0.02498,0.22800,0.01396,0.01219,0.01947,0.04188,0.00484,25.42900,0.420383,0.785714,-6.836811,0.269866,2.223719,0.147491]]
x= par_scaler.transform(x)
par_model.predict(x)

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0], dtype=int64)